name: AWS

on:
  push:
    branches: ["main"]

jobs:
  paiky_build:
    runs-on: ubuntu-latest #! REQUIRED FOR DOCKER - IT ALREADY HAS DOCKER INSTALLED
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Login to Docker Hub                                 #$ Quotes if password contains special characters
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p "${{ secrets.DOCKERHUB_PASSWORD }}" #$ Read Notion, I left awesome content for DockerHub
      - name: Build image
        run: docker build -t priapisman677/test_dockerhub . #$ Read Notion, I left awesome content for DockerHub
      - name: Push image to Docker Hub
        run: docker push priapisman677/test_dockerhub:latest #* We will only pull the :latest in the EC2 instance. 



  #$ In this specific case it is not mandatory to make it to different jobs. It would be mandatorily when you need to execute commands in a different environment (runs-on). However I did it here to separate concerns logically. 
  deploy:
    needs: paiky_build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.EC2_HOST}} #$ for SSH, don't include port unless not using :22 . Example: 132.84.129.77
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_SSH_PRIVATE_KEY}} #! I BELIEVE it should be the private one for solving the ssh-secret and authenticate to the EC2 instance
          #$ "script" is part of appleboy, "|" is part of YAML and means:  “Treat the following indented lines as a single multiline string.”  like "echo \"line 1\"\necho \"line 2\""
          script: |                                              #$ Quotes if password contains special characters
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p "${{ secrets.DOCKERHUB_PASSWORD }}"
            docker pull priapisman677/test_dockerhub:latest
            #* Removing previous CONTAINER
            docker rm -f node_app || true #$ "|| true" is ONLY to avoid throwing an error if the container is not running
            #* Running new CONTAINER


                                  #¡ PICK THE CORRECT PORTS 
                                  #¡ FOR NOW JUST PRACTICE WITH GITHUB ACTIONS BUT YOU NEED TO CHANGE SOME THINGS IN ALL PROJECTS
            docker run -d --name node_app -p 3002:3002  priapisman677/test_dockerhub:latest






