name: AWS git fetch
on:
  push:
    branches: ['master']

jobs:
  run_in_EC2:
    runs-on: ubuntu-latest
    environment: Test_Paiky_Environment #$ Optionally, create  a github environment to avoid duplicating secrets across repositories.
    steps:
      # - name: ENV TEST
      #   run: echo "$REPO_PATH" && echo "$REPO_NAME"

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.EC2_HOST}} #$ for SSH, don't include port unless not using :22 . Example: 132.84.129.77.
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_SSH_PRIVATE_KEY}}
          passphrase: ${{ secrets.EC2_SSH_PRIVATE_KEY_PASSPHRASE }} #$ Only if required.

          script: |
            #* Declaring variables for EC2 (it doesn't have access to "env")
            UNIQUE_APP_NAME="${{ secrets.UNIQUE_APP_NAME }}"  #! UNIQUE_APP_NAME must be all lowercase and without underscores for Docker to accept it.
            REPO_PATH="${{ github.repository }}"  #$ Example: # gives "dev-miguel/repo-name". We will use this to clone the repo initially. 
            DOCKER_PORT="${{ secrets.DOCKER_PORTS }}"  #! This is the only thing that needs to be changed repo-wise.
            cd ~/vsCodeMain

            #* If the is no desired-folder with .git, it means the repo doesn't exist so we clone it INTO A DESIRED FOLDER NAME.
            [ -d "$UNIQUE_APP_NAME/.git" ] || git clone git@github.com:$REPO_PATH.git "$UNIQUE_APP_NAME" #! You need to use a key that DOESN'T USE A PASSPHRASE.
            cd "$UNIQUE_APP_NAME" 
            git fetch origin 
            git merge origin/master
            #* Build and Run Docker
            sudo docker rm -f "$UNIQUE_APP_NAME" || true
            sudo docker build -t "$UNIQUE_APP_NAME" .
            sudo docker run -d --name "$UNIQUE_APP_NAME" -p "$DOCKER_PORT":"$DOCKER_PORT"  "$UNIQUE_APP_NAME"



            

