name: AWS git fetch
on:
  push:
    branches: ['master']

jobs:
  run_in_EC2:
    runs-on: ubuntu-latest
    environment: Test_Paiky_Environment #$ Optionally, create  a github environment to avoid duplicating secrets across repositories.
    env:
      REPO_PATH: ${{ github.repository }} #* Example: # gives "dev-miguel/repo-name". We will use this to clone the repo initially. 
      REPO_NAME: ${{ github.event.repository.name }} #$ Theoretically we could also make this as a Github secret. But since this provided out of the box we prefer using this.
      DOCKER_PORT: $ {{secrets.DOCKER_PORTS}}
    steps:
      # - name: ENV TEST
      #   run: echo "$REPO_PATH" && echo "$REPO_NAME"

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.EC2_HOST}} #$ for SSH, don't include port unless not using :22 . Example: 132.84.129.77.
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_SSH_PRIVATE_KEY}}
          passphrase: ${{ secrets.EC2_SSH_PRIVATE_KEY_PASSPHRASE }} #$ Only if required.

          script: |
            cd ~/vsCodeMain/$REPO_NAME
            [-d .git ] || git clone git@github.com:$REPO_PATH.git . #* If the is no .git, it means the repo doesn't exist so we clone it.
            git fetch origin 
            git merge origin/master

            #* Build and Run Docker
            sudo docker rm -f "$REPO_NAME" || true
            sudo docker build -t "$REPO_NAME" .
            sudo docker run -d --name "$REPO_NAME" -p "$DOCKER_PORT":"$DOCKER_PORT"  "$REPO_NAME"



            

